### ISSUE TITLE
Cartoon illustrating line of sight effects on time delay, image separation?

### ISSUE THREAD

**Issue by drphilmarshall** [tommasotreu/AARV#12]

**Comment by drphilmarshall** [comment]
Somehow illustrate effect of line of sight structures on deflection angles, so that mass inference is wrong... Needs thought.

**Comment by tommasotreu** [comment]
I think this is not necessary given the time pressure, and we should drop the idea

**Comment by drphilmarshall** [comment]
Agreed.
