### ISSUE TITLE
Read and discuss Jee, Suyu, Komatsu's papers

### ISSUE THREAD

**Issue by tommasotreu** [tommasotreu/AARV#26]

**Comment by drphilmarshall** [comment]
[Jee, Komatsu & Suyu, JCAP 2015](http://adsabs.harvard.edu/abs/2015JCAP...11..033J)

Reference added to bibtex file.

**Comment by drphilmarshall** [comment]
Also [Jee et al 2015](http://adsabs.harvard.edu/abs/2015arXiv150903310J) on astro-ph, for cosmological forecasts.

**Comment by drphilmarshall** [comment]
PS. I notice the cosmology forecast paper is not yet accepted.

**Comment by drphilmarshall** [comment]
Done! I have notes to discuss tomorrow.
