### ISSUE TITLE
Add sigma to theory discussion

### ISSUE THREAD

**Issue by tommasotreu** [tommasotreu/AARV#27]

**Comment by drphilmarshall** [comment]
Hmm - OK, see what you think: I made minimal changes to both `theory.tex` and `modeling.tex`, including updating our inline capitalized notes to self. Reading what you have in the modeling section, I think it makes most sense to restrict the theory section to just contain generic background material, and keep all specific assumptions in the measurement sections. I think this will keep things clean: we wouldn't want people to think that you _have_ to assume spherical Jeans equation for the lens galaxy stellar dynamics and an elliptically-symmetric power law density profile deflection model! I think this is a good archetypal model to lay out in the modeling section, though: from there we can discuss Suyu et al 2014's 2-component test, Birrer et al's perturbations, Barnabe's approach to 2D kinematics and so on. What do you think? Feel free to start a new issue!
