### ISSUE TITLE
Make figure showing DA vs DDT for Suyu chains

### ISSUE THREAD

**Issue by tommasotreu** [tommasotreu/AARV#28]

**Comment by drphilmarshall** [comment]
Ciao @tommasotreu ! Check out the [notebook I made using the B1608 chains that Sherry sent me.](https://github.com/tommasotreu/AARV/blob/issue/28/DdtDaPlot/figures/DdtDa.ipynb) My interpretation is at the bottom of this (long) page.  Let me know what you think!

**Comment by drphilmarshall** [comment]
Add vertical lines to show precisions.
