### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by drphilmarshall** [tommasotreu/AARV#3]
I found myself adding the word "lens", both when updating the [repository README](https://github.com/tommasotreu/AARV) and also the latex. What do you think? Are we allowed to do this?

**Comment by tommasotreu** [comment]
I think we are allowed to change the title if we like. But I prefer it without "lens" for conciseness "Time delay cosmography" just sounds better to me. But you are the native speaker so if you think it's odd I am happy to go along with it.

**Comment by tommasotreu** [comment]
We could even go for "Time delay cosmology", which is perhaps less accurate but more accessible to people, as I often find people do not know what cosmography means (sadly, most of our colleagues don't have a proper command of ancient greek).

**Comment by drphilmarshall** [comment]
OK, let's stick with time delay cosmography then. It has a nice parallel
with time delay distance, too.
