### ISSUE TITLE
Check and finalize Section 7, including adding new references if missing

### ISSUE THREAD

**Issue by tommasotreu** [tommasotreu/AARV#37]

**Comment by drphilmarshall** [comment]
Ciao @tommasotreu ! I went through the paper on the plane, and just merged with your edits and pushed again. I had a go at the conclusions too, adding a statement about precision and also a conclusion about systematics - this really has to be there, as I think we can all agree we have work to do on them! :-) See what you think.

**Comment by tommasotreu** [comment]
I will go through this now and finalize.

**Comment by tommasotreu** [comment]
I liked it but I turned things a bit more positive. Also, "valuable contribution" sounds like we are bringing doughnuts.. At least let's say decisive contribution, if you really don't wanna say discover something. Although I think discover is better.

**Comment by tommasotreu** [comment]
I changed it to discovery. Sorry. Let's at least be upbeat ourselves..

**Comment by drphilmarshall** [comment]
Right: but I don't think we should imply that time delay cosmography alone will make the discovery! Accurate cosmology is already and will continue to be a multi-probe effort. How about "time delay cosmography will help enable us to make new discoveries about the fundamental nature of space time" ?
