### ISSUE TITLE
make list of initial readers

### ISSUE THREAD

**Issue by tommasotreu** [tommasotreu/AARV#38]

**Comment by tommasotreu** [comment]
First collaborators:

Sherry Suyu
Frederic Courbin
Adriano Agnello
Leon Koopmans
Chris Fassnacht
Edi Rusu
Roger Blandford
Georges Meylan
Malte Tewes
Matt Auger
Alessandro Sonnenfeld
Stefan Hilbert
Dominique Sluse
Josh Frieman
Liz Buckley-Geer
Tom Collett
Ken Wong

Then colleagues:

Chuck Keeton
Chris Kochanek
Paul Schechter
Peter Schneider
Leonidas Moustakas
Eric Linder
Joel Primack (he asked)
Neal Jackson
Curtis McCully
- STRIDES, LSST DESC, TDC Good Teams mailing lists

**Comment by drphilmarshall** [comment]
I added a few names by editing your comment above!

**Comment by tommasotreu** [comment]
Great. I like this list. Let's send it to the first group this week-end, and to the second group after a week, I propose
