### ISSUE TITLE
Paste plan into latex file

### ISSUE THREAD

**Issue by drphilmarshall** [tommasotreu/AARV#4]
From the [Google doc here](https://docs.google.com/document/d/19XQJTHRYl9VoLWFIccVaoA9ydh2uvPz4Xx62yANwWnU/edit#)

**Comment by drphilmarshall** [comment]
Ciao - issues are all done! When you paste the plan into the texfile, would you mind also moving it into the top level directory please? I don't think we need a 'draft' subfolder, we're only working on one document in this project. Thanks!

**Comment by tommasotreu** [comment]
Hi, I have done it. But I do not know what you have mind regarding moving? Can you please move it yourself? I don't want to screw up stuff on github. Moving makes me nervous...

**Comment by drphilmarshall** [comment]
Done! I just `mv`-ed the files, and then `git add` and `git commit`-ed
them. Oh and I added a Makefile as well. Thanks!
