### ISSUE TITLE
Check and finalize Section 4, including adding new references if missing

### ISSUE THREAD

**Issue by tommasotreu** [tommasotreu/AARV#46]
I have done all my parts and gone through yours. I am happy with it. If you are happy we can consider this done. Otherwise, please feel free to edit/comment.

**Comment by drphilmarshall** [comment]
I think we are missing two things:
1. A brief description of how Suyu et al actually combined lensing and dynamics - I think it's worth pointing out that the mass models are not strictly identical! We should refer to Barnabe's work to show that this can be done better - and cite his "crash test" results too, to show the value of testing against numerical sims.
2. The environment section is still lacking historical context: we need to add refs to Keeton, Zabludoff and Momcheva's work, and then also McCully and Wong's reconstruction efforts. Sorry! I didn't get a chance to look at this, and thought you were taking care of it. 

I'll be in the car driving to HMB for the next hour - do you want to take a look at this? If not I can have a go when I get home. Feel free to re-assign back :-)

**Comment by tommasotreu** [comment]
Hi Phil, thanks for taking care of this. I think 1 is too much detail frankly. I remember you suggested to add this but I decided against it. I worry we are already too detailed on some things. As for 2 I would prefer if you could take care of it, by adding a few sentences to 4.3. I will take care of the rest.
