### ISSUE TITLE
Request permission, original PDFs for figures

### ISSUE THREAD

**Issue by tommasotreu** [tommasotreu/AARV#47]
List of figures, with references. Check boxes when we have permission and original PDF.
- [x] Fig. 1 Comparison between one of the early light curves (left panel, from Vanderriest et al, 1989)
  - [x] Author permission
  - [x] Journal permission
  - [x] Original PDF in `figures/Vanderriest89_fig5.pdf`
- [x] Fig. 1 A modern light curve from COSMOGRAIL (right panel, from Tewes et al, 2013b)
  - [x] Author permission
  - [x] Journal permission
  - [x] Original figures in `figures/Tewes13-fig4_part1.pdf` and `figures/Tewes13-fig4_part2.pdf`
- [x] Fig. 2 Comparison between imaging data available in the 90s (left panel, from Schechter et al, 1997) 
  - [x] Author permission
  - [x] Journal permission
  - [x] Original figure in `figures/pg115_blowup.png`
- [x] Fig. 2 and in the most recent studies (middle and right panels, from Suyu et al, 2014))
  - [x] Author permission
  - [x] Journal permission
  - [x] Original figure in `figures/Suyu14_fig1.pdf`
- [x] Fig. 4 Geometric and general relativistic contributions to the time delay, from (Treu and Ellis, 2015)
  - [x] Author permission
  - [x] Journal permission
  - [x] Original figure in `figures/delays.pdf`
- [x] Fig. 5 Cosmological parameter constraints from time delay lenses, from Suyu et al (2013)
  - [x] Author permission
  - [x] Journal permission
  - [x] Original figure in `figures/Suyu13_fig11.pdf`
- [x] Fig. 6 Fisher matrix forecasts of cosmological parameters, from Coe and Moustakas (2009)
  - [x] Author permission
  - [x] Journal permission
  - [x] Original figure in `figures/Coe+Moustakas09_fig14.pdf`
- [x] Fig. 7 Fisher matrix forecasts for a future time delay lens sample from Jee et al (2015b)
  - [x] Author permission
  - [x] Journal permission
  - [x] Original figure in `figures/Jee16_fig5b.pdf`
- [x] Fig. 9 Cosmological forecast for step 2 in the roadmap, courtesy of S.H. Suyu.
  - [x] Author permission
  - [x] Original figures in: `figures/planck_olcdm_c22lenses_stats.jpg`, `figures/wmap9_olcdm_c22lenses_stats.jpg`, `figures/planck_wcdm_c22lenses_stats.jpg`, `figures/wmap9_wcdm_c22lenses_stats.jpg`

**Comment by tommasotreu** [comment]
All permissions requested except Vanderriest. I could not find him.. do you know anyone on that author list?

**Comment by drphilmarshall** [comment]
No! Hmm. Maybe the journal can help us out there? I'd close this for now if I were you.

**Comment by tommasotreu** [comment]
Ok, let's ask the journal but let's leave the issue open so that we don't forget.

**Comment by drphilmarshall** [comment]
OK, I have contacted three of the authors from Vanderriest et al 1989. The first author seems to have left the field though, so our PDF screengrab may have to suffice. There is no arxiv version with source files, only an ADS PDF.

**Comment by drphilmarshall** [comment]
Good! We are all set bar the journal permissions. I'll see how Frank is doing on that.

**Comment by drphilmarshall** [comment]
Frank says we are good to go!
