### ISSUE TITLE
mass-sheet degeneracy - time delay impact

### ISSUE THREAD

**Issue by sibirrer** [tommasotreu/AARV#58]
Isn't equation (5) and (6) only valid when the mass-sheet is at the lens plane? I might be wrong. If not, it could be beneficial to explicitly mention this assumption that goes into the time-delay transformation. See e.g. McCully 2014 for a more generalized version.

I am happy to discuss this.

**Comment by drphilmarshall** [comment]
Thanks Simon! Excellent point. I made clear that the equations are for the single plane case, and provided refs as you suggest.
