### ISSUE TITLE
H0 measurements as a function of time, cautionary figure

### ISSUE THREAD

**Issue by drphilmarshall** [tommasotreu/AARV#6]

**Comment by tommasotreu** [comment]
I am thinking this might not be necessary and might be a bit overkill. Let's discuss on friday.

**Comment by drphilmarshall** [comment]
I'm inclined to agree with you. What time's good to talk on Friday? If you
can do afternoon that'd be better for me!

**Comment by tommasotreu** [comment]
We arr scheduled to talk tomorrow at 10am. I am at UCOACon Friday...

Tommaso
