### ISSUE TITLE
lensed strong lenses

### ISSUE THREAD

**Issue by sibirrer** [tommasotreu/AARV#60]
section 3, "The form of the mas sheet ..."

LOS perturbers between observer and lens can make the lens appeared lensed itself (non-linear shear effect). External convergence to the lens itself (change of D_d). These effects are so far ignored in the time-delay analysis but might lead to biases (in particular when D_d is changed by foreground mass structure). It might be worth mentioning that. Just a suggestion. Maybe in another section.

**Comment by drphilmarshall** [comment]
Good idea. I added a short paragraph in the "Outlook: Accuracy" section. Thanks, Simon!
