### ISSUE TITLE
4.2.1 infinite S/N

### ISSUE THREAD

**Issue by sibirrer** [tommasotreu/AARV#63]
In section 4.2.1, "In principle, for data with infinite signal-to-noise..."
I don't think that even in this case, one can determine the difference in Fermat potential as one does not know the source scale and therefore does not really know the deflection angle.
Or am I wrong with this?

**Comment by drphilmarshall** [comment]
No, I think you are right. Sentence now reads:

> "In principle, for data with infinite signal-to-noise ratio and resolution one could imagine integrating the gradient of the deflection angle along a path between a pair of images to obtain the difference in Fermat potential, up to a mass sheet transformation (Section\ref{sec:theory})."

Thanks for pointing this out!
