### ISSUE TITLE
4.2.2 lens modeling techniques

### ISSUE THREAD

**Issue by sibirrer** [tommasotreu/AARV#64]
4.2.2: Birrer et al. 2015 does not require additional regularization. In fact, the number of shapelets and the scale length beta defines the regularisation. In that sense, it is a regularization imprinted basis set.

**Comment by drphilmarshall** [comment]
Good point - I was getting ahead of myself. I added a footnote as follows:

> "\footnote{In the case of the shapelet basis set,
> regularization is effectively achieved through choosing the number of basis
> functions to use as well as the scale of the underlying Gaussian. An
> alternative scheme would be to assign a less uninformative prior for the
> shapelet coefficients, but this has not yet been tested.}"

A suggestion for your research program there, Simon! :-)

Thanks!
