### ISSUE TITLE
external shear estimates from strong lens image reconstruction

### ISSUE THREAD

**Issue by sibirrer** [tommasotreu/AARV#65]
section 4.3 environment and LOS structure

Information about the environment can also be gained when measuring the external shear in the strong lens image reconstruction. This has been done in e.g. Suyu et al 2013.

Just for your information: I am going to publish an analysis of a strong lens in the cosmos field where I measured the shear to the lens (including the non-linear effects on the lens model) and the source. Taking this information into account leads to roughly double the precision in the convergence estimate.

**Comment by drphilmarshall** [comment]
Thanks again, Simon - added a note on Suyu et al 2013. Looking forward to reading your paper.
