### ISSUE TITLE
Section 1 draft text: introduction

### ISSUE THREAD

**Issue by drphilmarshall** [tommasotreu/AARV#7]

**Comment by tommasotreu** [comment]
Done! Take a look and see if it's too big picture.

**Comment by drphilmarshall** [comment]
No, I think that's good. I see you commented out the cosmological context - that's OK with me, but were you just thinking of postponing that discussion till section 5 or 6, or dropping it altogether?

**Comment by tommasotreu** [comment]
Let's discuss all this at 1:30 today ok? Our usual Skype call 

Tommaso
