### ISSUE TITLE
Typos and phrasing

### ISSUE THREAD

**Issue by mtewes** [tommasotreu/AARV#73]
In complement to Simon's list:
- Page 15, Section 4.2.3, first sentence: [...] provide a qualitatively different input and **are** therefore very valuable [...]
- Page 5, Section 2, noughties instead of naughties (?)

Phrasing (of course I might be completely wrong here, just ignore if so...)
- Page 2, "infamous unknown unknowns". I wonder if this notion is so infamous that no explanatory sentence is required. Also the reader might wonder how unknown unknowns can be controlled at all at the level of systematic errors.
- Page 5, Section 2: "[...] random errors grossly underestimated the total uncertainty [...]". At first read I found this phrasing a bit too short. The estimation of systematic errors was often neglected. No, actually it's quite OK.

**Comment by drphilmarshall** [comment]
Thanks Malte! All these are now fixed.
