### ISSUE TITLE
TDC1 PyCS summary

### ISSUE THREAD

**Issue by mtewes** [tommasotreu/AARV#74]
Section 4.2.1, page 13, "The PyCS team tried a three-step approach (visual inspection and interactive curve shifting, followed by spline fitting, followed by an additional spline model regression analysis of the residuals) [...]"

I'm not sure about the "three steps", and what the "additional spline model regression" is. Maybe two steps ?
--> "The PyCS team tried a two-step approach (visual inspection and interactive curve shifting, followed by automated analyses based on spline model regressions for the AGN variability and the microlensing) [...]"

**Comment by vbonvin** [comment]
I agree.

It seems the 3rd step mentioned here is mistaken with the regression difference technique. I would suggest the following addition:
--> "The PyCS team tried a two-step approach (visual inspection and interactive curve shifting, followed by automated analyses based on spline model fitting or Gaussian process regression for the AGN variability and the microlensing) [...]"

**Comment by vbonvin** [comment]
After reflection, I'm in favor of mtewes first version.

**Comment by drphilmarshall** [comment]
Thank you both for clarifying this! I've adopted the wording that you recommend.
