### ISSUE TITLE
Importance of regular sampling in monitoring campaigns

### ISSUE THREAD

**Issue by vbonvin** [tommasotreu/AARV#75]
In addition of long monitoring campaigns, a regular sampling is also a key factor if one wants to increase the precision and accuracy of the measurements. 

Sec 4.1, page 11:
Long **and regular** monitoring campaigns can build up high statistical significance as more and more light curve features can be brought into play. However, such long campaigns are difficult to
carry out in practice, because a large number of guaranteed observing nights **evenly spaced**
are required (even if the total exposure time is modest).

**Comment by drphilmarshall** [comment]
Good point, thank you Vivien!
