### ISSUE TITLE
Sect. 4.2.2.: about Bayesian modeling

### ISSUE THREAD

**Issue by dsluse** [tommasotreu/AARV#77]
In the list of hybrid modeling approaches, may be add Tagore and Jackson 2016 (2016MNRAS.457.3066T). The paper on the modeling of 0047 by Brewer and Lewis 2006 (2006ApJ...651....8B) provides also one of the first attempt to use a Bayesian approach to model lensed systems with Einstein rings.

**Comment by drphilmarshall** [comment]
Thanks Dominique! Good suggestions, now included.
