### ISSUE TITLE
Section 2 draft text: brief history of time delay cosmography

### ISSUE THREAD

**Issue by drphilmarshall** [tommasotreu/AARV#8]

**Comment by tommasotreu** [comment]
I drafted it. Phil, please read it before writing the rest of the text, since this defines the scope of this review (i.e. modern measurements). I still need to add a figure and will create an issue for that.

**Comment by drphilmarshall** [comment]
I think its a good idea that we focus on the modern measurements. Do we need more detail in the history section, to make up for the fact that we move quickly on to 2000 and beyond? One place it might be good is where we point out the early papers that tried to use the Rings, or do ensemble analyses?
